branches:
  only:
  - master
language: node_js
node_js:
- 9.10.0
before_install:
- sudo apt-get update
- sudo apt-get install -y python3 python3-pip
- pip3 install awscli --upgrade --user
install:
- npm install
script:
- npm run-script build
- npm run-script deploy
