branches:
  only:
  - master
language: node_js
node_js:
- 9.10.0
before_install:
- sudo apt-get update
- sudo apt-get install -y python3 python3-pip
- pip3 install awscli --upgrade --user
install:
- npm install
script:
- npm run-script build
- npm run-script deploy
env:
  global:
  - secure: p7SHdvxJ/EfZri5xyP+90WTD74Tph8Y6KqHEsgOba7IxEX3vfl4e7DsmYggD+vCHegLKUNgOj4t+stnOH6aLsl6gVr+mNYjxemGIbkzgY2BXUlRuRnTDJX9Ih/KE2Gy2T/NPk8Dhd0alPQTW8yD5hjiXjCAdBMxrqDJptbgvKZhPNd6CobXhvXrkUgnDoIB3dQ80swgRhgOrGEVo+qjGkfcv6ax83m+Ax4pA1fP0nGczVwmVSBhTa3skmNFmCwrNTea5k1I68YXfpaSyHVUXJ+WENAhlUhgVTqg46z/aFU3/5lzmAviUf+kJqkWz4JABx5DuByxbZ8FwlS3FGFUAq/S9ruCV4Qplol7dCpZsUiMxsydnInPDEnfYv6DKRzaAI3QLdXP5iAPy0+wuHQ7fxgkgEjLlAmDG6F2nFwkoCcWv1tWswBoDPJ3e5X5LQFJw1N3SkRUGWdNV+E26x9Ra1R28Y7Hihf8wGmojXrR2d6rsGCk2LCRtKOGThV2k1y4eTET6UTPJwgM/A5jTU6u57KOpp6LGXTBGyki3eDeuB+XJbpDkSYJOLTlngVmY34kgX9mRkVjenkiZRWjR6a4kJY61gY7TtReifevwBJP5AZk3W6/glPrBfazGTg0RkRFjVir9MAUlMVR0T7tMNWVflFlcXQ27e7vDtoqAWW4hnLw=
  - secure: k0wK6sLKzjDDLhM8zNuwz6ekr+eywrtRAqnTxlvJMYQp4S9b/PzngYvIbzXWsyF0u/xqd5A/NYKw5yIwLlAiGWXgRDqHLmD0BNuO56t+rNQF7Lq8YzbbOKCH8iTY3AqG6DRrg2IY7dqIo35K01NrI/1T4EEGqild4kmuELyVP//DRrn5eM9lfjn4QgrzcAlbqwfKjOjuJ69WTMAmH7eBFt17bqDSyO5CmGdamikl+vu3QoIyh5m5DmH5EKkIJySlRY+FF+5MmHP+kybwA5mW1ZJuNCyYgU4+IE9TTLO6JfI+2mkvRiZlr3fja+2wgVBgJVM6vvWyyQ0YmimcK8n7maLyW0QG9Q9oOpCZAmaU5jKsQVmkeA7T2Z08Kz2JiIoTvQrKr11+XICSX757ITutdRWaEC6jQVqbEjf5p3SpRebAYvcbXnNvQniqkSNEuLjPoHwVBD1NiDVizKi0eVndYFHh+kdawtKS54HLDcNAa2dqF0AuJOIVnK2sR5ZGA65AuV/LFoMPYeThdj+m+Ez/s9IVlujy99hcQvF9q9z/+2TrCh0S7XcksJhOAS3JeAIaUs2qLgFZ2+r0vb6iPX4h3p+njvjdOai5OzW0GFZOW0nUm6dQefzH0Kiet3hY8EFH5jqaX6pqCw96v/JmMFT4BHm85HC8jfdCGbVqdXK/pPM=
