export const UPDATE_TOKEN = "UPDATE_TOKEN";
export const UPDATE_RIDES = "UPDATE_RIDES";
export const LOADING_RIDES = "LOADING_RIDES";
export const LOADING_RIDES_DONE = "LOADING_RIDES_DONE";
export const UPDATE_DATES = "UPDATE_DATES";
export const INVALID_START_DATE = "INVALID_START_DATE";
export const VALID_START_DATE = "VALID_START_DATE";
export const RESET_RIDES = "RESET_RIDES";
